name: Deploy Frontend

on:
  push:
    branches:
      - master  # ili main, zavisi od tvoje glavne grane

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout koda
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Login na Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 3. Build i push frontend slike sa 'latest' tagom
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./front/my-app
          file: ./front/my-app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/weather-frontend:latest

      # 4. Deploy na server koristeÄ‡i SSH password
      - name: Deploy on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd demo-app
            docker-compose pull
            docker-compose down
            docker-compose up -d
